apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: backstage.io
  annotations:
    github.com/project-slug: 'spotify/backstage'

spec:
  type: website
  lifecycle: production
  owner: guest
